development:
  adapter: pg
  encoding: utf8
  database: project_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: sqlite3
  encoding: unicode
  database: project_test
  pool: 5
  username: 
  password:

production:
  adapter: pg
  encoding: unicode
  database: project_production
  pool: 5
  username: 
  password:
