# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12b1fdc7ad73a3bab1880a585185624faf14bc352c27d96d6bb8317dc2aa8b2b151385533736e19c15b1d4a64e2b8a1c2883043059a630575af6757afb896011

test:
  secret_key_base: 4709885f6bb8534e0a40718eab0b83b92856709773141b78040c4871b3010d0838e283e85c2ac916b99f3e5168c09d5a0f215d4afaebc6bf5720abfdd2e1fb93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
